logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE
        engine:
          transaction:
            internal: TRACE
        resource:
          jdbc:
            internal: TRACE
      springframework:
        transaction: TRACE
        data: TRACE
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG

