spring:
  jpa:
    properties:
      hibernate:
        show_sql: false
logging:
  level:
    root: ERROR
    org:
      hibernate:
        SQL: ERROR
        type:
          descriptor:
            sql: ERROR
        engine:
          transaction:
            internal: ERROR
        resource:
          jdbc:
            internal: ERROR
      springframework:
        test:
          jdbc: DEBUG
        transaction: ERROR
        data: ERROR
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
