#debug: true
server:
  port: 8081
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'

spring:
  jpa:
    generate-ddl: false
    open-in-view: false

    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: a

logging:
  level:
    org:
#      hibernate: TRACE
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE
        engine:
          transaction:
            internal: TRACE
        resource:
          jdbc:
            internal: TRACE
      springframework:
        transaction: TRACE
        data: TRACE
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG

#balanceUpdateReservation.findAndPessimisticWriteLockByReservationCode: "SELECT b FROM balanceUpdateReservation b WHERE b.reservationCode = :reservationCode"
#balanceUpdateConfirm.findWhatever: "SELECT b, c FROM balanceUpdateReservation b, balanceUpdateConfirm c WHERE b.reservationCode = :reservationCode AND c.balanceUpdateReservationEntity.id = b.id"