server:
  port: 8081
spring:
  jpa:
    generate-ddl: false
    open-in-view: false

    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: a

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE
      springframework:
        transaction: TRACE
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
